workflows:
  flutter-workflow:
    name: Flutter Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      flutter: stable

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Create key.properties
        script: |
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=$STORE_FILE" >> android/key.properties

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build Android App Bundle
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - ranjithkumarr522@gmail.com
        notify:
          success: true
          failure: true
